feat: update publish registry docs
ArcBlock/abtnode-docs pull request #112
Opened 2021-11-22 14:35 UTC by LancelotLewis

- 使用新版的 registry 流程来做说明
- bump-version 在 approved 之后添加

2021-11-23 01:41 UTC, wangshijun requested changes

2021-11-23 01:41 UTC, wangshijun commented on src/developer/publish-blocklets/index.md
> +   - Use `blocklet config set registry [registryUrl]` command to configure the target Blocklet Registry
更名为 Store 之后，这里是不是得改掉？

`blocklet config set store storeUrl`

2021-11-23 01:41 UTC, wangshijun commented on src/developer/publish-blocklets/index.md
> +   - Use `blocklet config set registry [registryUrl]` command to configure the target Blocklet Registry
Blocklet Registry 这些干脆都改成 Blocklet Store 吧

2021-11-23 01:43 UTC, LancelotLewis commented on src/developer/publish-blocklets/index.md
> +   - Use `blocklet config set registry [registryUrl]` command to configure the target Blocklet Registry
ok

2021-11-23 01:49 UTC, LancelotLewis commented on src/developer/publish-blocklets/index.md
> +   - Use `blocklet config set registry [registryUrl]` command to configure the target Blocklet Registry
> Blocklet Registry 这些干脆都改成 Blocklet Store 吧

这里涉及到 Blocklet Store 的访问地址是否需要变更，比如 store.blocklet.dev ？

2021-11-23 02:07 UTC, LancelotLewis commented on src/developer/publish-blocklets/index.md
> +   - Use `blocklet config set registry [registryUrl]` command to configure the target Blocklet Registry
待 blocklet registry 更名后再更新此文档

2021-11-27 06:40 UTC, LancelotLewis commented on src/developer/publish-blocklets/index.md
> +   - Use `blocklet config set registry [registryUrl]` command to configure the target Blocklet Registry
已更改

2021-11-28 01:57 UTC, wangshijun approved these changes

2021-11-28 02:27 UTC, merged